### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by cuamckuu** [cube2222/octosql#288] opened 2022-08-03 17:05 UTC
Have golang installed
```
$ go version
go version go1.18 windows/amd64
```

Using command from readme:
```
$ go install -u github.com/cube2222/octosql
flag provided but not defined: -u
usage: go install [build flags] [packages]
Run 'go help install' for details.
```

After removing `-u`:
```
$ go install github.com/cube2222/octosql
go: 'go install' requires a version when current directory is not in a module
        Try 'go install github.com/cube2222/octosql@latest' to install the latest version
```

After adding `@latest`:
```
$ go install github.com/cube2222/octosql@latest
go: github.com/cube2222/octosql@latest (in github.com/cube2222/octosql@v0.9.2):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by cube2222** [comment] 2022-08-03 21:44
Hey @cuamckuu!

This seems to be a duplicate of #282

Please either download a precompiled binary from the releases page or clone + install.

**Closed by cube2222** 2022-08-03 21:44 UTC
